
services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=k6org
      - DOCKER_INFLUXDB_INIT_BUCKET=k6
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=super-secret-token
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - ./influxdb/config:/etc/influxdb2
    networks:
      - k6-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,yesoreyeram-infinity-datasource
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    networks:
      - k6-network

  k6:
    image: k6v2
    container_name: k6
    entrypoint: ["k6"]
    command: ["run", "/scripts/test.js"]
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=xk6-influxdb=http://influxdb:8086
      - K6_INFLUXDB_ORGANIZATION=k6org
      - K6_INFLUXDB_BUCKET=k6
      - K6_INFLUXDB_INSECURE=true
      - K6_INFLUXDB_TOKEN=super_secret_token
      - K6_INFLUXDB_PUSH_INTERVAL=5s


      - K6_OUT_DEBUG=true
      - K6_LOG_LEVEL=debug

    dns: 8.8.8.8
    dns_search: .
    volumes:
      - ./scripts:/scripts
    depends_on:
      - influxdb
    networks:
      - k6-network
networks:
  k6-network:
    driver: bridge
    name: k6-network
    attachable: true
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
    driver_opts:
      com.docker.network.driver.mtu: 1500
      com.docker.network.bridge.enable_icc: "true"

volumes:
  influxdb-data:
  grafana-data:
